[tool.poetry]
name = "boardgame-rag"
version = "0.1.0"
description = ""
authors = ["seilj <been22026@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
elasticsearch = "^8.17.1"
langchain-community = "^0.3.17"
langchain = "^0.3.18"
python-dotenv = "^1.0.1"
langchain-chroma = "^0.2.1"
langchain-openai = "^0.3.4"
langchain-cohere = "^0.4.2"
langchain-elasticsearch = "^0.3.2"
selenium = "^4.28.1"
langgraph = "^0.2.71"
pymongo = "^4.11.1"
pymupdf = "^1.25.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
